services:
  - type: web
    name: chat-app
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    plan: free
    branch: main
    staticPublishPath: build
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
